### ISSUE TITLE
使用过程的两个问题

### ISSUE THREAD

**Issue by jinnchen** [coderfe/qiniu-fig-bed#4]
首先这个插件很好用，然后我在三天的使用过程中遇到了两个问题：

1. 图片地址会加上vsc的安装路径作为前缀？

1. 上传好图片后生产的markdown文字中小括号的链接没有`http://`？

如有需要，我可以提供截图

**Comment by coderfee** [comment]
我没有发现这俩问题，麻烦提供一下截图。这是我上传之后生成的链接：

![snipaste_20170621_213746](https://user-images.githubusercontent.com/18255987/27386959-f346d938-56c9-11e7-98cd-c31783f9cb10.png)

**Comment by jinnchen** [comment]
![qiniu1.png](http://ooflxktgp.bkt.clouddn.com/qiniu1.png)
第二点应该就不用截图了

我的环境是：
window10
vscode 1.13.1

**Comment by noahcao** [comment]
same problem as the second one of @jinnchen (no preffix ‘http://’ in the link) . Is this problem has been figured? 

My environment:

windows 10
vscode 1.24.1

**Comment by coderfee** [comment]
@noahcao Is your configuration like this?

![qiniu-fig-bed-configuration](https://user-images.githubusercontent.com/18255987/42092735-894c964c-7bdc-11e8-9ef9-25f11d59975a.png)

**Comment by noahcao** [comment]
@coderfe  Yes, But I settled this problem with the procedure: uninstall the extension -> reboot my machine -> reinstall the extension -> re-edit the config file.

Thx for your help and the good extension tool
